name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Checkout MaLiLib
      uses: actions/checkout@v3
      with:
        repository: ZacSharp/malilib-forge
        ref: ddd3ea8c621010b81346be8aea06e7e5d63c559e
        path: malilib

    - name: Checkout Litematica
      uses: actions/checkout@v3
      with:
        path: litematica

    - name: Build MaLiLib
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: malilib
        cache-read-only: ${{github.event_name == 'pull_request'}}

    - name: Build Litematica
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: litematica
        cache-read-only: ${{github.event_name == 'pull_request'}}

    - name: Upload MaLiLib Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Malilib Artifacts
        path: malilib/build/libs/*

    - name: Upload Litematica Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Litematica Artifacts
        path: litematica/build/libs/*
